name = "Silly Sandbox 1.18"
author = "owo.digital"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "594b09a5ac06a3fb148fc890bf55d052149aad8a299649ebf70b7fce75c1a3da"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
