name = "Silly Sandbox 1.18"
author = "owo.digital"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0a52b0bf85cd375b6379d1ade6e251edd0b6745d85966d95387a5ffd8fdbf93"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
