name = "Silly Sandbox 1.18"
author = "owo.digital"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4613867b0048373e6cc0bf68ef0e177d783a609df38fd3edd60b755b16882b6b"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
