name = "Silly Sandbox 1.18"
author = "owo.digital"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ca5d73d8d229ae91793ba0ddba4d76a0ad70ff5a59d567f934cc78a6e6b4a1a"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
