name = "Silly Sandbox 1.18"
author = "owo.digital"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f94b47ddf25bfe1f2338c2ab27982b558122402544c106c4d68338e56ce82a8a"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
