name = "Silly Sandbox 1.18"
author = "owo.digital"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a519ce16bddb959dbf56e577bb5232d7ad0cbc440eab5daea3527f284a6a472"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
