name = "Silly Sandbox 1.18"
author = "owo.digital"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6dd5af9fa1edfdb60a3547e8393bc33ddab9d67fff4305a7a6520a2f0f58a5a"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
