name = "Silly Sandbox 1.18"
author = "owo.digital"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e78a1335427edece93d42c2a91ff815cc9f74ca9e3d5629b721344c2e2cb7e00"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
