name = "Silly Sandbox 1.18"
author = "owo.digital"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a00d6c30c2e86444bf22aa26c5832fd0ac034d36c1e9900fac9fca1fc71488d"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
