name = "Silly Sandbox 1.18"
author = "owo.digital"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7916501fccdb04476bf365023b833c8b494399aea85f68400a20df9fbcb7f4f"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
