name = "Silly Sandbox 1.18"
author = "owo.digital"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be8d397ca4048b4597192eff24aa2fb860e2535cb64278bd8b19eead5b646a89"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
