name = "Silly Sandbox 1.18"
author = "owo.digital"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af14faf0df21d584f80a6f8ba986da569db7ca88bed4b376a0c7d1d623600161"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
