name = "Silly Sandbox 1.18"
author = "owo.digital"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9208f90d3911657ff743ca1a0e8deeafcbd67c605540e5057fc6f4139bad85de"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
