name = "Silly Sandbox 1.18"
author = "owo.digital"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f71e0049b4b5201603a54330bc1cb3d555cdd223f7efe748c3a5a438b3d4ff4f"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
